### ISSUE TITLE
Suport QtWebEngine for 6.4

### ISSUE THREAD

**Issue by rafatosta** [flathub/com.riverbankcomputing.PyQt.BaseApp#151]
is there a plan for QtWebEngine support for version 6.4?

**Comment by JakobDev** [comment]
I would also like to have  QtWebEngine for 6.4, but the Problem is, that it depends on the [QtWebEngine BaseApp]( https://github.com/flathub/io.qt.qtwebengine.BaseApp), but the QT 6 Version of this BaseApp is currently completely unmaintained. @tinywrkb [started working on this](https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/159), but he has currently not much time. Updating the QtWebEngine BaseApp to 6.4 would also mean updating a lot of Patches, which I'm not capable of. As long as there is no new Maintainer for the  QtWebEngine 6 BaseApp who updates it the 6.4 is found, there's nothing I can do.

**Comment by rafatosta** [comment]
Thank you very much for the feedback

**Comment by JakobDev** [comment]
QtWebEngine is now supported in the 6.5 branch
